# Generated by Django 5.1.4 on 2024-12-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='models',
            field=models.ManyToManyField(related_name='actors', to='movies.movie'),
        ),
    ]
