# Generated by Django 5.1.4 on 2024-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='models',
            field=models.ManyToManyField(related_name='movies_actors', to='movies.movie'),
        ),
    ]
