# Generated by Django 5.1.4 on 2024-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_actors_alter_actor_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='models',
            new_name='movies',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors_movies', to='movies.actor'),
        ),
    ]
