# Generated by Django 5.1.4 on 2024-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
